defaults:
  - base_colmap
camera_model: PINHOLE # SIMPLE_RADIAL
use_gpu: 
matching_method: exhaustive
gt_poses_dir: 
# /srv/galene0/sr572/palace_of_westminster/dense/sparse
angular_error: 15
translation_error: 0.25
# output_dir: "testdir" <- override parent class defaults
# TODO: move them to have a data preprocessing separate config
seed: 0 
sample_size: 
image_list:
video_sample_step: